### ISSUE TITLE
[FEATURE] Dynamic input of `key`, `secret` and `region`

### ISSUE THREAD

**Issue by ThomasTJdev** [disruptek/atoz#5]
Hi @disruptek 

Currently the library uses `os.getEnv("AWS_ACCESS_KEY_ID", AWS_ACCESS_KEY_ID)` for multiple procs. Any specific reason for this? I would like to be able to specify the `key`, `secret` and `region` without accessing the environmental variables.

If that's okay with you, I can prepare a PR. Suggestions:
* Duplicated `atozSign()` proc for specific values
* Specific signing proc, `atozSignGetValues(key="", secret="", region="")`, which checks the params for values, otherwise returns the environmental
* Expand current `atozSign()` proc's params with `key="", secret="", region=""` - if empty then use environmental

**Comment by ThomasTJdev** [comment]
Well.. I had a one time use for this. We should follow AWS procedure by using environmental or the config-file. Closing the issue.

**Comment by disruptek** [comment]
Ah, well the code generator isn't in this repo, but it takes the OpenAPI YAML as input and defines the signing proc and whatnot before generating the Nim source.  I should probably add it, but it seems kinda moot since my OpenAPI module doesn't yet support the version 3.0 now used by AWS and published in the OpenAPI directory repository...
